app/account/models.py
from app import db
from flask_login import UserMixin

'''
    # 用户表
    username    用户名（主键）
    password    密码
'''
class User(UserMixin, db.Model):
    __tablename__ = "user"

    username = db.Column(db.String(20), primary_key=True)
    password = db.Column(db.String(256), nullable=False)

app/account/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, EqualTo, Length

# 用户注册
class RegisterForm(FlaskForm):
    username = StringField(
        "昵称",
        validators=[
            DataRequired()           
            ],
        render_kw = {
            "class":"form-control",
            "placeholder":"请输入昵称",
            "maxlength":"40"
            }
        )
    password1 = PasswordField(
        "密码",
        validators=[
            DataRequired(),
            Length(min=8,max=16,message="密码必须为8-16位")
            ],
        render_kw={
            "class":"form-control",
            "placeholder":"请输入密码",
            "maxlength":"40"
            }
        )
    password2 = PasswordField(
        "重复密码",
        validators=[
            DataRequired(),
            EqualTo("password1", message="两次输入的密码不一致!")
            ],
        render_kw={
            "class":"form-control",
            "placeholder":"请再次输入密码",
            "maxlength":"40"
            }
        )
    submit = SubmitField(
        "注册",
        render_kw={
            "class": "btn btn-primary"
            }
        )

# 用户登录
class LoginForm(FlaskForm):
    username = StringField(
        "昵称",
        validators=[
            DataRequired()
            ],
        render_kw = {
            "class":"form-control",
            "placeholder":"请输入昵称",
            "maxlength":"40"
            }
        )
    password = PasswordField(
        "密码",
        validators=[
            DataRequired()
        ],
        render_kw={
            "class":"form-control",
            "placeholder":"请输入密码",
            "maxlength": "40"
        }
    )
    submit = SubmitField(
        "登录",
        render_kw={
            "class": "btn btn-primary"
            }
        )

# 修改密码
class ChangePwdForm(FlaskForm):
    oldpwd = PasswordField(
        "原密码",
        validators=[
            DataRequired()
        ],
        render_kw={
            "class":"form-control",
            "placeholder":"请输入原密码",
            "maxlength": "40"
        }
    )
    password1 = PasswordField(
        "新密码",
        validators=[
            DataRequired(),
            Length(min=8,max=16,message="密码必须为8-16位")
            ],
        render_kw={
            "class":"form-control",
            "placeholder":"请输入新密码",
            "maxlength":"40"
            }
        )
    password2 = PasswordField(
        "重复密码",
        validators=[
            DataRequired(),
            EqualTo("password1", message="两次输入的密码不一致!")
            ],
        render_kw={
            "class":"form-control",
            "placeholder":"请再次输入新密码",
            "maxlength":"40"
            }
        )
    submit = SubmitField(
        "修改密码",
        render_kw={
            "class": "btn btn-primary"
            }
        )

app/account/__init__.py
from flask import Blueprint

account_bp = Blueprint('account', __name__,template_folder='templates')

from .views import *

app/account/views.py
from flask import render_template, flash, redirect, url_for, session

from app import app, db, g_config, login
from . import account_bp
from .models import User
from .forms import RegisterForm, LoginForm, ChangePwdForm

from werkzeug.security import generate_password_hash, check_password_hash


@login.user_loader
def load_user():
    return

@account_bp.route("/", methods=["GET"])
@account_bp.route("/index", methods=["GET"])
def index():
    return redirect(url_for("account.login"))

@account_bp.route("/login", methods=["GET","POST"])
def login():
    form = LoginForm()
    username = form.username.data
    password = form.password.data
    if form.submit.data:
        user = User.query.get(username)
        if user is None or not check_password_hash(user.password, password):
            flash("昵称或密码错误！", category="danger")
        else:
            session.clear()
            session["username"] = username
            flash("登录成功！", category="info")
            return redirect(url_for("account.panel"))

    return render_template(
        "index.html",
        title = "登录",
        form = form
    )

@account_bp.route("/signup", methods=["GET","POST"])
def signup():
    form = RegisterForm()
    if form.submit.data:
        username = form.username.data
        pwd1 = form.password1.data
        pwd2 = form.password2.data
        user = User.query.get(username)
        if user is not None:
            flash("用户已存在！", category="danger")
        elif pwd1 != pwd2:
            flash("两次密码不一致！", category="danger")
        else:
            user = User(username=username, password=generate_password_hash(pwd1))
            db.session.add(user)
            try:
                db.session.commit()
                flash("注册成功！", category="info")
                return redirect(url_for("account.login"))
            except Exception as e:
                app.logger.info(f"注册失败: {e}")
                db.session.rollback()
                flash(f"注册失败: {e}", category="danger")

    return render_template(
        "signup.html",
        title = "注册",
        form = form
    )

@account_bp.route("/changepwd", methods=["GET","POST"])
def changepwd():
    form = ChangePwdForm()
    if form.submit.data:
        pwd1 = form.password1.data
        pwd2 = form.password2.data
        if pwd1 != pwd2:
            flash("两次密码不一致！", category="danger")
        else:
            # TODO: 密码加密
            try:
                user = User.query.filter(User.username == session["username"]).update({
                    "password": generate_password_hash(pwd1)})
                db.session.commit()
                flash("密码修改成功，请重新登录！", category="info")
                return redirect(url_for("account.login"))
            except Exception as e:
                app.logger.info(f"改密失败: {e}")
                db.session.rollback()
                flash(f"改密失败: {e}", category="danger")

    return render_template(
        "changepwd.html",
        title = "修改密码",
        form = form
    )

@account_bp.route("/logout", methods=["GET"])
def logout():
    session.clear()
    return redirect(url_for("account.login"))

@account_bp.route("/panel", methods=["GET","POST"])
def panel():
    return render_template(
        "panel.html",
        title = "控制面板",
        tablelinks = g_config.tablelinks
    )

app/account/templates/changepwd.html
{% extends "base.html" %}

{% block app_content %}
<div class="form-screen">
	<a href="{{url_for('account.index')}}" class="easion-logo">
		<span>•ω•&nbsp;&nbsp;学生管理系统</span>
	</a>
	<div class="card account-dialog">
		<div class="card-header bg-primary text-white">修改密码</div>
		<div class="card-body">
			<form method="post">
				{{form.csrf_token}}
				<div class="form-group">
					<span>旧密码：</span>
					{{form.oldpwd}}
				</div>
				<div class="form-group">
					<span>新密码：</span>
					{{form.password1}}
				</div>
				<div class="form-group">
					<span>重复密码：</span>
					{{form.password2}}
				</div>
				<div class="account-dialog-actions">
					<a href="{{url_for('account.panel')}}" class="btn btn-primary">{{form.submit}}</a>
				</div>
			</form>
		</div>
	</div>
</div>
{% endblock app_content %}

app/account/templates/index.html
{% extends "base.html" %}

{% block app_content %}
<div class="form-screen">
	<a href="{{url_for('account.index')}}" class="easion-logo">
		<span>•ω•&nbsp;&nbsp;学生管理系统</span>
	</a>
	<div class="card account-dialog">
		<div class="card-header bg-primary text-white">用户登录</div>
		<div class="card-body">
			<form method="post">
				{{ form.csrf_token }}
				<div class="form-group">
					<span>昵称：</span>
					{{form.username}}
				</div>
				<div class="form-group">
					<span>密码：</span>
					{{form.password}}
				</div>
				<br>
				<div class="account-dialog-actions">
					<div  class="btn btn-primary">{{form.submit}}</div>
					<a class="account-dialog-link" href="{{url_for('account.signup')}}">去注册</a>
				</div>
			</form>
		</div>
	</div>
</div>
{% endblock app_content %}

app/account/templates/panel.html
{% extends "dash.html" %}

{% block dash_app %}
<div>
	<h2 class="dash-title" align="center">
		<br><span>•ω•&nbsp;&nbsp;欢迎来到学生管理系统！</span>
	</h2>
	<div align="center">
		本系统由&nbsp;
		<a href="https://gitlab.com/FrancisOWO/flaskdemo" target="_blank">FrancisOWO</a>
		&nbsp;开发
	</div>
	<br><div align="center">version 1.0</div>
</div>
{% endblock dash_app %}

app/account/templates/signup.html
{% extends "base.html" %}

{% block app_content %}
<div class="form-screen">
	<a href="{{url_for('account.index')}}" class="easion-logo">
		<span>•ω•&nbsp;&nbsp;学生管理系统</span>
	</a>
	<div class="card account-dialog">
		<div class="card-header bg-primary text-white">用户注册</div>
		<div class="card-body">
			<form method="post">
				{{form.csrf_token}}
				<div class="form-group">
					<span>昵称：</span>
					{{form.username}}
				</div>
				<div class="form-group">
					<span>密码：</span>
					{{form.password1}}
				</div>
				<div class="form-group">
					<span>重复密码：</span>
					{{form.password2}}
				</div>
				<div class="account-dialog-actions">
					<a class="btn btn-primary">{{form.submit}}</a>
					<a class="account-dialog-link" href="{{url_for('account.login')}}">去登录</a>
				</div>
			</form>
		</div>
	</div>
</div>
{% endblock app_content %}